name: PHP Quality Assurance

on:
    push:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**psalm.xml'
            - '**composer.json'
    pull_request:
        paths:
            - '**workflows/php-qa.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**psalm.xml'
            - '**composer.json'
    workflow_dispatch:
        inputs:
            jobs:
                required: true
                type: choice
                default: 'Run all'
                description: 'Choose jobs to run'
                options:
                    - 'Run all'
                    - 'Run PHPCS only'
                    - 'Run Psalm only'
                    - 'Run lint only'
                    - 'Run static analysis (PHPCS + Psalm)'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-php:
        uses: inpsyde/reusable-workflows/.github/workflows/lint-php.yml@main
        strategy:
            matrix:
                php: ["8.0", "8.1", "8.2"]
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs == 'Run all') || (github.event.inputs.jobs == 'Run lint only')) }}
        with:
            PHP_VERSION: ${{ matrix.php }}

    coding-standards-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs != 'Run lint only') && (github.event.inputs.jobs != 'Run Psalm only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/coding-standards-php.yml@main

    static-code-analysis-php:
        if: ${{ (github.event_name != 'workflow_dispatch') || ((github.event.inputs.jobs != 'Run lint only') && (github.event.inputs.jobs != 'Run PHPCS only')) }}
        uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
